### ISSUE TITLE
make calculatePhat a public method 

### ISSUE THREAD

**Issue by nsteinme** [peterzh/NeuroGLM#4]
why not?

**Comment by peterzh** [comment]
Currently the method is accessible to any subclass of GLM (using the Access = {?GLM} syntax) . I'm inclined to keep it non public because it is more of a utility function than a standalone process and I'm keen to ensure the code is kept uncluttered unless there's a pressing need. It would be easy to make the method public via a subclass however.

----- Reply message -----

**Comment by nsteinme** [comment]
Maybe someone wants to make a prediction from the model for some contrast
conditions of interest? This seems like a pretty fair thing to expect a
user to want to do.

**Comment by peterzh** [comment]
Done, but in the future I may revert to making the method public only through custom subclasses if the code expands significantly.
